platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.dev.pkhamdee.com/library/concourse-helper
    tag: 3

inputs:
  - name: app-src

run:
  path: app-src/ci/tasks/scan-code/run.sh