apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: covid-data-prod
  namespace: default
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: master
      url: git@github.com:pkhamdee/covid-data.git
  successBuildHistoryLimit: 10
  tag: harbor.dev.pkhamdee.com/cna-covid/covid-data:0.0.1-SNAPSHOT
