platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonji/gcp-k8s
    tag: latest

params:
  GKE_DEPLOY_KEY:
  GKE_DEPLOY_SA_EMAIL:
  GKE_CLUSTER_NAME:
  GKE_CLUSTER_ZONE:
  GKE_PROJECT_ID:
  DEFINITION_FILE_PATH:

inputs:
  - name: app-src
  - name: deployment-definition

run:
  path: app-src/covid/ci/tasks/push-deployment-gcp/run.sh