platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonji/aws-k8s
    tag: latest

params:
  AWS_PROVISION_CLUSTER_SA_ACCESS_KEY_ID:
  AWS_PROVISION_CLUSTER_SA_SECRET_ACCESS_KEY:
  EKS_CLUSTER_NAME:
  EKS_CLUSTER_REGION:
  DEFINITION_FILE_PATH:

inputs:
  - name: app-src
  - name: deployment-definition

run:
  path: app-src/covid/ci/tasks/push-deployment-aws/run.sh