---
resources:
  - name: app-src
    type: git
    source:
      uri: git@github.com:pkhamdee/covid-data.git
      branch: ((git-branch))
      private_key: ((github-repo-update-data-key))

jobs:
  - name: run-unit-tests
    public: false
    plan:
      - get: app-src
        trigger: true
      - task: test
        file: app-src/ci/tasks/unit-tests/task.yml