---
resource_types:  
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: app-src
    type: git
    source:
      uri: git@github.com:pkhamdee/covid-data.git
      branch: ((git-branch))
      private_key: ((github-repo-update-data-key))

  - name: notify-team
    type: slack-notification
    source:
      url: ((slack_webhook_url))
jobs:
  - name: run-unit-tests
    plan:
      - get: app-src
        trigger: true
      - task: test
        file: app-src/ci/tasks/unit-tests/task.yml
    on_failure:
      put: notify-team
      params:
        text: >
          :x: Unit Test failing on the covid-data repo
          Job: <http://((concourse_host))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|ID>    