platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: app-src
  - name: covid-data

params:
  DATA_FOLDER_PATH: covid-data
  COVID_APP_RESOURCES_FOLDER_PATH: updated-app-src/covid/src/main/resources/data

outputs:
  - name: updated-app-src

run:
  path: app-src/covid/ci/tasks/update-data/run.sh